#!/usr/bin/env python3
"""Generate FM8.plus's modified forms as C headers (build/gui/forms/frm<id>.h) from the LOCAL FM8.

The forms are Native Instruments' data, so they are never checked in: this script rebuilds them on
the developer's machine from their own FM8.exe (decompile -> edit -> recompile -> embed), and the
shims pick the headers up when present (Core::serveForms) and fall back to the in-memory byte patch
when not. Run after any change to EDITS, then rebuild.

    python tools/gen_forms.py [FM8.exe]
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fm8gui as g  # noqa: E402

INSTALLED = r"C:\Program Files\Native Instruments\FM8\FM8.exe"

# The edits, as (form id) -> list of (control id, callable(control dict)).
def shift_x(dx):
    def f(c):
        c["base"]["x1"] += dx
        c["base"]["x2"] += dx
    return f

EDITS = {
    5:  [(5, shift_x(-11))],   # FormMain header: move the FM8 wordmark 11px left to make room for the "+"
    15: [(5, shift_x(-11))],   # FormMainCompact: same wordmark control
}


def main():
    pe = sys.argv[1] if len(sys.argv) > 1 else (INSTALLED if os.path.exists(INSTALLED) else g.DEFAULT_PE)
    rsrc = g.extract(pe, os.path.join(g.GUI_DIR, "rsrc"))
    out = os.path.join(g.GUI_DIR, "forms")
    os.makedirs(out, exist_ok=True)
    for fid, edits in EDITS.items():
        form = g.parse(g.load_frm(rsrc, fid))
        by_id = {c["id"]: c for c in form["controls"]}
        for cid, fn in edits:
            fn(by_id[cid])
        blob = g.build(form)
        path = os.path.join(out, f"frm{fid}.h")
        rows = [", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"// Generated by tools/gen_forms.py from {os.path.basename(pe)} FRM {fid}; not part of the repo.\n"
                    f"#pragma once\nstatic const unsigned char kFrm{fid}[{len(blob)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n")
        print(f"FRM {fid}: {len(edits)} edit(s) -> {path} ({len(blob)} bytes)")


if __name__ == "__main__":
    main()
