#!/usr/bin/env python3
"""Generate FM8.plus's modified GUI resources as C headers (build/gui/forms/*.h) from the LOCAL FM8.

The forms and artwork are Native Instruments' data, so they are never checked in: this script
rebuilds them on the developer's machine from their own FM8.exe and the shims serve them through
FM8's import table (Core::serveForms). Two kinds of resource make the "FM8+" button:

  FRM 5 / FRM 15  the header bars, with the wordmark control moved left and widened to hold the "+"
  PICTURE 193     the wordmark bitmap itself, widened by the same amount with the "+" drawn on

FM8 then draws, scales and hit-tests the "+" as part of its own logo; src/core/ui.cpp only watches
for a click inside that rect. Run after any change here, then rebuild.

    python tools/gen_forms.py [FM8.exe]
"""
from __future__ import annotations

import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fm8gui as g  # noqa: E402

INSTALLED = r"C:\Program Files\Native Instruments\FM8\FM8.exe"

# Geometry of the "FM8+" wordmark. The stock control and picture are 95x23 at (21,35); we move it
# LOGO_SHIFT px left (there is only 17px of free space before the sound-name label) and grow it
# PLUS_W px to the right. src/core/ui.cpp repeats these three numbers to hit-test the click.
LOGO_PIC = 193
LOGO_SHIFT = 11
PLUS_W = 22

# The "+" itself: a 12-vertex slanted cross, sheared 10 degrees to the right to sit italic beside
# FM8's own wordmark, in the logo's own blue-grey. Centre is in picture pixels.
PLUS_COLOUR = (107, 125, 134, 255)
PLUS_CX, PLUS_CY = 107.4, 12.46
PLUS_HALF, PLUS_THICK, PLUS_SLANT = 7.37, 1.515, 0.1767


def widen_logo(c):
    c["base"]["x1"] -= LOGO_SHIFT
    c["base"]["x2"] += PLUS_W - LOGO_SHIFT


EDITS = {
    5: [(5, widen_logo)],    # FormMain header
    15: [(5, widen_logo)],   # FormMainCompact: the same wordmark control
}


def plus_picture(src_png):
    """The stock wordmark widened by PLUS_W with the "+" drawn on, as PNG bytes."""
    from PIL import Image, ImageDraw
    src = Image.open(src_png).convert("RGBA")
    out = Image.new("RGBA", (src.width + PLUS_W, src.height), (0, 0, 0, 0))
    out.paste(src, (0, 0))
    a, t, k = PLUS_HALF, PLUS_THICK, 8      # k = supersampling factor for the antialiased edges
    xs = (a, t, t, -t, -t, -a, -a, -t, -t, t, t, a)
    ys = (-t, -t, -a, -a, -t, -t, t, t, a, a, t, t)
    pts = [((PLUS_CX + x - y * PLUS_SLANT) * k, (PLUS_CY + y) * k) for x, y in zip(xs, ys)]
    big = Image.new("RGBA", (out.width * k, out.height * k), (0, 0, 0, 0))
    ImageDraw.Draw(big).polygon(pts, fill=PLUS_COLOUR)
    out.alpha_composite(big.resize(out.size, Image.LANCZOS))
    buf = io.BytesIO()
    out.save(buf, "PNG")
    return buf.getvalue()


def write_header(path, name, blob, note):
    rows = [", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// Generated by tools/gen_forms.py from {note}; not part of the repo.\n"
                f"#pragma once\nstatic const unsigned char {name}[{len(blob)}] = {{\n    "
                + ",\n    ".join(rows) + "\n};\n")
    print(f"{name}: {len(blob)} bytes -> {path}")


def main():
    pe = sys.argv[1] if len(sys.argv) > 1 else (INSTALLED if os.path.exists(INSTALLED) else g.DEFAULT_PE)
    rsrc = g.extract(pe, os.path.join(g.GUI_DIR, "rsrc"))
    out = os.path.join(g.GUI_DIR, "forms")
    os.makedirs(out, exist_ok=True)
    base = os.path.basename(pe)
    for fid, edits in EDITS.items():
        form = g.parse(g.load_frm(rsrc, fid))
        by_id = {c["id"]: c for c in form["controls"]}
        for cid, fn in edits:
            fn(by_id[cid])
        write_header(os.path.join(out, f"frm{fid}.h"), f"kFrm{fid}", g.build(form), f"{base} FRM {fid}")
    png = plus_picture(os.path.join(rsrc, "PICTURE", f"{LOGO_PIC}.png"))
    write_header(os.path.join(out, f"pic{LOGO_PIC}.h"), f"kPic{LOGO_PIC}", png, f"{base} PICTURE {LOGO_PIC}")


if __name__ == "__main__":
    main()
